import type { Project } from "@/types"

export const projects: Project[] = [
  {
    id: "3d-portfolio",
    title: "3D Portfolio Website",
    description: "Interactive 3D portfolio website built with Three.js, React, and Tailwind CSS.",
    image: "https://fra.cloud.appwrite.io/v1/storage/buckets/6818cc88002c3b1b0450/files/6818d4f7002f89efa849/view?project=6818cc3d000bc241cbfb",
    tags: ["React.js", "Three.js", "Tailwind CSS", "Vite"],
    demoLink: "https://portfolio.example.com",
    codeLink: "https://github.com/username/portfolio",
    featured: true,
  },
  {
    id: "ecommerce",
    title: "E-commerce Platform",
    description: "Full-stack e-commerce platform with product management, cart functionality, and payment integration.",
    image: "https://fra.cloud.appwrite.io/v1/storage/buckets/6818cc88002c3b1b0450/files/6818d4f7002f89efa849/view?project=6818cc3d000bc241cbfb",
    tags: ["Next.js", "MongoDB", "Stripe", "Tailwind CSS"],
    demoLink: "https://shop.example.com",
    codeLink: "https://github.com/username/ecommerce",
    featured: true,
  },
  {
    id: "ai-image",
    title: "AI Image Generator",
    description: "Web application that generates images using AI based on text prompts.",
    image: "https://fra.cloud.appwrite.io/v1/storage/buckets/6818cc88002c3b1b0450/files/6818d4f7002f89efa849/view?project=6818cc3d000bc241cbfb",
    tags: ["React.js", "OpenAI API", "Node.js", "Express"],
    demoLink: "https://ai-image.example.com",
    codeLink: "https://github.com/username/ai-image-generator",
    featured: true,
  },
  {
    id: "task-app",
    title: "Task Management App",
    description: "Collaborative task management application with real-time updates and team features.",
    image: "https://fra.cloud.appwrite.io/v1/storage/buckets/6818cc88002c3b1b0450/files/6818d4f7002f89efa849/view?project=6818cc3d000bc241cbfb",
    tags: ["Vue.js", "Firebase", "Vuetify", "PWA"],
    demoLink: "https://tasks.example.com",
    codeLink: "https://github.com/username/task-app",
  },
  {
    id: "weather",
    title: "Weather Dashboard",
    description: "Real-time weather dashboard with location search and 7-day forecasts.",
    image: "https://fra.cloud.appwrite.io/v1/storage/buckets/6818cc88002c3b1b0450/files/6818d4f7002f89efa849/view?project=6818cc3d000bc241cbfb",
    tags: ["JavaScript", "Weather API", "Chart.js", "CSS"],
    demoLink: "https://weather.example.com",
    codeLink: "https://github.com/username/weather-app",
  },
  {
    id: "social-analytics",
    title: "Social Media Analytics",
    description: "Dashboard for tracking and analyzing social media performance across platforms.",
    image: "https://fra.cloud.appwrite.io/v1/storage/buckets/6818cc88002c3b1b0450/files/6818d4f7002f89efa849/view?project=6818cc3d000bc241cbfb",
    tags: ["React.js", "D3.js", "Node.js", "MongoDB"],
    demoLink: "https://analytics.example.com",
    codeLink: "#",
  },
]
